version: '3'

services:

  las:
    container_name: las
    build: ./las/
    #command: tail -F anything # keep it running
    entrypoint: ['sh', '/data/web/las_setup.sh']
    volumes:
      - ./las:/data/web
      #- assets:/assets
      - las_static:/collected_static
      - lasstatus:/las_status
    working_dir: /data/web
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - lasmongodb1
      #- graphdb

  lasredis:
    container_name: lasredis
    image: redis:alpine
    expose:
      - "6379"
    restart: always
  

  lasmongodb3:
    image: mongo:4
    restart: always
    container_name: lasmongodb3
    env_file:
      - .env
    volumes:
      - lasmongodata3:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rslas", "--bind_ip_all" ]

  lasmongodb2:
    image: mongo:4
    restart: always
    container_name: lasmongodb2
    env_file:
      - .env
    volumes:
      - lasmongodata2:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rslas", "--bind_ip_all"]
  

  lasmongodb1:
    image: mongo:4
    restart: always
    container_name: lasmongodb1
    env_file:
      - .env
    volumes:
      - lasmongodata1:/data/db
    expose:
      - "27017"
    ports:
      - "27018:27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rslas", "--bind_ip_all"]


  lasmongosetup:
    image: mongo:4
    container_name: lasmongosetup
    depends_on:
      - lasmongodb1
    volumes:
      - lasstatus:/data/
      - ./mongo-setup:/config
    entrypoint: [ "bash",  "/config/mongo-setup.sh"]

  # nginx:
  #   build: ./nginx-pagespeed/
  #   restart: always
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/app/nginx.conf
  #     - ./nginx/conf:/etc/nginx/app/conf_app/
  #     - las_static:/collected_static
  #     #- assets:/assets
  #     #- ./las/_config/static_to_move_away:/static
  #     #- ./las/_config/static_to_move_away/img:/img
  #     #- ./las/static:/las_static
  #     - ./nginx/certificate:/ssl
  #     #- tinymce:/tinymce
  #     #- django_tinymce:/django_tinymce
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     - MAKE_J=4
  #     - NGINX_VERSION=1.15.5
  #     - PAGESPEED_VERSION=1.12.34.2
  #     - LIBPNG_VERSION=1.6.29
  #     - NGINX_INCLUDE_PATH=/etc/nginx/app/conf_app/*.conf
  #     - NGINX_DEFAULT_SERVER=off
  #     - NGINX_FASTCGI_GEOIP=off
  #     - NGINX_PAGESPEED=on
  #     - NGINX_PAGESPEED_IMG=on
  #     - NGINX_PAGESPEED_JS=on
  #     - NGINX_PAGESPEED_CSS=on
  #     - NGINX_PAGESPEED_STORAGE=file

  flower:
    container_name: flower
    image: mher/flower
    command: ["flower", "--broker=redis://lasredis:6379/0", "--port=8888"]  
    ports:  
      - 8888:8888

  celerylas:
    build: ./las/
    command: celery worker -A LAS -l info --concurrency=3
    working_dir: /code
    volumes:
      - ./las:/code
    depends_on:
      - lasmongodb1
      - lasmongodb2
      - lasmongodb3
      - lasmongosetup
      - lasredis
volumes:
  las_static:
  #assets:
  lasmongodata1:                                                                                  
  lasmongodata2:
  lasmongodata3:
  lasstatus:
  ##lasgraphdb: